# Site settings
title: RORLa-API Team Blog
email: admin@rorlab.org
description: "ROR Lab. 웹사이트 리뉴얼 오픈 소스 프로젝트의 팀블로그입니다."
baseurl: ""
url: "http://http://rorlabnew.github.io/"
github: "RORLabNew/rorla_api"
facebook: "groups/rorlabrenewal/"

# Build settings
markdown: redcarpet
permalink: pretty
