# Site settings
title: ROR Lab Renewal Project Team Blog
email: hschoidr@gmail.com
description: "ROR Lab. 웹사이트 리뉴얼 오픈 소스 프로젝트의 팀블로그입니다."
baseurl: ""
url: "http://http://rorlabnew.github.io/"
github: "RORLabNew/rorla_api"
facebook: "groups/rorlabrenewal/"

# Build settings
markdown: kramdown
permalink: pretty
