# Site settings
title: RORLa-API Team Blog
email: admin@rorlab.org
description: "ROR Lab. 웹사이트 리뉴얼 오픈 소스 프로젝트의 팀블로그입니다."
baseurl: ""
url: "http://http://rorlabnew.github.io/"
github: "RORLabNew/rorla_api"
facebook: "groups/rorlabrenewal/"
proseio: "http://prose.io/#RORLabNew/rorlabnew.github.io/"

# Build settings
markdown: redcarpet
permalink: pretty

# Prose
prose:
  rooturl: '_posts'
  siteurl: 'http://http://rorlabnew.github.io/'
  relativeLinks: ''
  media: 'images'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
